// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskOps.Infrastructure.Persistence;

#nullable disable

namespace TaskOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaskOpsDbContext))]
    [Migration("20260528042642_AddIssueCommentsAndActivityLogs")]
    partial class AddIssueCommentsAndActivityLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskOps.Domain.Modules.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssigneeId", "OrganizationId");

                    b.HasIndex("OrganizationId", "Priority");

                    b.HasIndex("OrganizationId", "Status");

                    b.HasIndex("ProjectId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ProjectId", "Number")
                        .IsUnique();

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.IssueActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ActorMemberId");

                    b.HasIndex("ActorMemberId", "OrganizationId");

                    b.HasIndex("CommentId", "OrganizationId");

                    b.HasIndex("IssueId", "OrganizationId");

                    b.HasIndex("OrganizationId", "IssueId", "CreatedAt");

                    b.ToTable("IssueActivities");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.IssueComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorMemberId");

                    b.HasIndex("AuthorMemberId", "OrganizationId");

                    b.HasIndex("DeletedByMemberId", "OrganizationId");

                    b.HasIndex("IssueId", "OrganizationId");

                    b.HasIndex("OrganizationId", "IssueId", "CreatedAt");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Organizations.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Identity.RefreshToken", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.Issue", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Organizations.OrganizationMember", "Assignee")
                        .WithMany("AssignedIssues")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskOps.Domain.Modules.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOps.Domain.Modules.Organizations.OrganizationMember", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaskOps.Domain.Modules.Projects.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.IssueActivity", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Organizations.OrganizationMember", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorMemberId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaskOps.Domain.Modules.Issues.IssueComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaskOps.Domain.Modules.Issues.Issue", "Issue")
                        .WithMany("Activities")
                        .HasForeignKey("IssueId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Comment");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.IssueComment", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Organizations.OrganizationMember", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorMemberId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskOps.Domain.Modules.Organizations.OrganizationMember", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByMemberId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaskOps.Domain.Modules.Issues.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DeletedBy");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Organizations.OrganizationMember", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Organizations.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOps.Domain.Modules.Identity.User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Projects.Project", b =>
                {
                    b.HasOne("TaskOps.Domain.Modules.Organizations.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Identity.User", b =>
                {
                    b.Navigation("OrganizationMemberships");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Issues.Issue", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Organizations.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Organizations.OrganizationMember", b =>
                {
                    b.Navigation("AssignedIssues");
                });

            modelBuilder.Entity("TaskOps.Domain.Modules.Projects.Project", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
